# Reward Params
reward:
  give_final_reward: False
  max_final_reward: 20
  min_final_reward: -20
  max_step_reward: 0
  min_step_reward: -1.25

# Vehicles' Communication Range Param
communicaion_range: 24

# Ambulance-Related Params
ambulance:
  amb_start_x: -50
  amb_goal_x: 50
  amb_max_vel: 1
  amb_max_acc: 0.0333
  rel_amb_y_min: -24 #CATION: this SHOULD be within the vehicles' communication range
  rel_amb_y_max: 9 #CATION: this SHOULD be within the vehicles' communication range

# Agent-Related Params
agent:
  agent_max_vel: 0.5
  agent_max_acc: 0.0167

# Enable Gazebo Gui Param
gazebo_gui: False
